version: '3.8'

services:
  # Databases
  mongodb:
    image: mongo:7.0
    container_name: streamhub-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - streamhub-network

  redis:
    image: redis:7.0-alpine
    container_name: streamhub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - streamhub-network

  # Core Services
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: streamhub-api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_gateway?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

  authentication-service:
    build:
      context: ./services/authentication-service
      dockerfile: Dockerfile
    container_name: streamhub-auth-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_auth?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_here
      - JWT_REFRESH_SECRET=your_refresh_secret_here
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

  user-management-service:
    build:
      context: ./services/user-management-service
      dockerfile: Dockerfile
    container_name: streamhub-user-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_users?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

  content-management-service:
    build:
      context: ./services/content-management-service
      dockerfile: Dockerfile
    container_name: streamhub-content-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_content?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

  live-streaming-service:
    build:
      context: ./services/live-streaming-service
      dockerfile: Dockerfile
    container_name: streamhub-streaming-service
    restart: unless-stopped
    ports:
      - "3004:3004"
      - "1935:1935"  # RTMP port
    environment:
      - NODE_ENV=development
      - PORT=3004
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_streaming?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

  video-processing-service:
    build:
      context: ./services/video-processing-service
      dockerfile: Dockerfile
    container_name: streamhub-video-service
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_video?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

  engagement-service:
    build:
      context: ./services/engagement-service
      dockerfile: Dockerfile
    container_name: streamhub-engagement-service
    restart: unless-stopped
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_engagement?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: streamhub-payment-service
    restart: unless-stopped
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_payment?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: streamhub-notification-service
    restart: unless-stopped
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=development
      - PORT=3008
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_notifications?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

  analytics-service:
    build:
      context: ./services/analytics-service
      dockerfile: Dockerfile
    container_name: streamhub-analytics-service
    restart: unless-stopped
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=development
      - PORT=3009
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/streamhub_analytics?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - streamhub-network

volumes:
  mongodb_data:
  redis_data:

networks:
  streamhub-network:
    driver: bridge